### ISSUE TITLE
[Discuss] Relationship between identity credentials, passkeys, and federation

### ISSUE THREAD

**Issue by timcappalli** [WICG/digital-credentials#25]
> Surfaced as a core discussion topic on the first call ([2023-10-04](https://github.com/WICG/identity-credential/wiki/2023-10-04-Meeting-Notes)).

Sub topics:

- should identity credentials, passkeys, and federation be surfaced to users in the same UI?
- sign in vs claims transfer

**Comment by timcappalli** [comment]
Sub topic: should identity credentials, passkeys, and federation be surfaced to users in the same UI?

**Comment by OR13** [comment]
I think people enjoy the feeling of safety, knowing their fingerprint is required to present a credential, because similar to imagining someone forging an ink signature, it feels safer to the user to know that their consent and fingerprint is required, as opposed to a threat actor stealing a password, or forging their ink signature.

**Comment by timcappalli** [comment]
This has been discussed across many venues including calls, IIW, TPAC, Fed ID WG, and WebAuthn WG. The direct interaction between these experiences is driven by the user agent and/or app platforms.

Mixed usage at the CredMan level can be supported in the future: https://github.com/w3c/webappsec-credential-management/issues/244#issuecomment-2327703428
