### ISSUE TITLE
Is there a case where requestIdentity() resolves with null?

### ISSUE THREAD

**Issue by ryanhargrove** [WICG/digital-credentials#53]
To me, it seems like throwing an exception if the user did not choose to share their mdoc / does not have one on their device is an awkward pattern (especially in Javascript with no exception types). Preferably, a call to `credentials.get()` should return an empty response if a user chose not to share an mdoc instead 

Psuedocode: 

```
try {
  const credential = await credentials.get(...);

  if (credential.hasResponse()) {
     // handle credential response
  }

  // do nothing
} catch (e) {
  // handle truly unexpected errors
}

```

**Comment by RByers** [comment]
Thanks for the feedback Ryan. I agree the common case of no matching credential (or the user cancelling) isn't really an "error". I think we want to be consistent with how the credential management API behaves, even though we're defining our own method (see [latest explainer](https://github.com/WICG/identity-credential/blob/main/digital-credentials-2-proposal.md#extensions-to-credential-management-api-requestidentity-method), `navigator.credentials.requestIdentity`).

I went reading through the credential management and webAuthn specs and it seems like the promise resolving to 'null' is what Credential Management actually [defines](https://www.w3.org/TR/credential-management-1/#abstract-opdef-ask-the-user-to-choose-a-credential), but WebAuthn overrides that to always thrown an exception

**Comment by marcoscaceres** [comment]
In payment request, this is an `AbortError`, which I think personally think is more logical for the user cancelling than returning null. However, there could be a situation whereby `null` is returned, but the user didn't abort the operation (or the operation was not aborted because of some other reason, like the UI timed out or something else caused the credentials sheet to go away).

**Comment by leecam** [comment]
I agree with Marcos here. I prefer the AbortError.
We get a lot of feedback that error reporting on webauthn isn't verbose enough. So if null can be returned for non-user cancelled events or no cred events, then we lose some of the fidelity in the error reporting

**Comment by ryanhargrove** [comment]
Will `requestIdentity()` differentiate when a user chooses not to share vs. when they have no credentials available? From what I've seen the API intentionally hides that difference

That is kind of why I think an exception isnt right here. I would think that a valid request to `requestIdentity` should return a normal response, and exceptions should be reserved for things like malformed requests into the API, or whatever else gets bubbled up from the lower level code

**Comment by marcoscaceres** [comment]
@ryanhargrove, you raise good points and I think we just need to map them out a bit because they have privacy implications. 

The API shouldn't reveal if the user has any (N) credentials. But you are correct in as far that the use may have a credential but may choose not to share it or any (user hits esc or otherwise closes the UI: "AbortError"). 

The user agent could present UI to enroll the user, eventually resulting in credential - or the user may choose to abort (AbortError). 

We could then say that the user decides to share "the null credential" (i.e., share nothing), even if they have a credential. I don't think anyone will actually support this kind of thing, but it's feasible. 

I think we should add this (nullable `.response`) _iff_ there is an implementation that actually supports such a thing.

**Comment by marcoscaceres** [comment]
I'd also like to revise what I wrote above... the UI timing out, the user doing something that results in the wallet/sheet automatically closing, etc. are all possibly "AbortErrors". It shouldn't be possible for an application to detect what the browser did (e.g., a timeout) or what the user did (hit escape or whatever). Just that the operation was aborted. 

It still holds (but need to be proven by implementation or strong argument) that there is a use case for returning a `null` value for the response.

**Comment by marcoscaceres** [comment]
I think we should consider closing this until such time that we have a case where we resolve with `null`. Adding a null-able in WebIDL is super trivial (it's literally just adding `?` to `Promise<DigitalCredential?>`) and we should cross that bridge when we get to it as we continue to spec things out. 

@ryanhargrove, wdyt?

**Comment by ryanhargrove** [comment]
Hi Marco,

Sure that sounds fine to me. Thank you all for the discussion!
