### ISSUE TITLE
Using CryptoKey for public keys - what are the restrictions?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/digital-credentials#56]
Right now, we had proposed passing around DOM strings for public keys... However, `CryptoKey` serves as a nice primitive we already have in the platform from Web Crypto. 

I think we can reuse the `crypto.subtle.subtle.importKey()` method to get the `CryptoKey`, which we can then pass into `requestIdentity()` as part of the `IdentityRequestOptions`.

**Comment by OR13** [comment]
Does this issue imply mandatory support for `jwk`, `pkcs8`, and `raw` ?

Does this forbid certificates?

**Comment by marcoscaceres** [comment]
I guess it would be whatever Web Crypto mandates for formats, as it's the one providing the API to create `CryptoKey`. We can further restrict that in our spec. 

However, new format support would need to get added to Web Crypto so we could use them (if needed).

**Comment by jogu** [comment]
Can someone confirm if using Cryptokey allows us to preserve potentially important information like the 'kid' from a JWK please? From a brief read of the API it looks like that information would be lost.

**Comment by marcoscaceres** [comment]
Note that nothing need be "lost"... we can just amend Web Crypto if we need to and something is important to us. 

What uses `kid` and why does it matter? (I know very little about JWK, so all 👂)

**Comment by jogu** [comment]
> Note that nothing need be "lost"... we can just amend Web Crypto if we need to and something is important to us.

Fair enough, but as per my comment on #49 I'm unclear why we even want to go in this direction.

> What uses kid and why does it matter? (I know very little about JWK, so all 👂)

It's a key identifier. The header of an encrypted JWT usually includes the keyid of the key that was used to perform the encryption, so that when the encrypted JWT arrives at the verifier's backend it knows which key to try decrypting it with. (There are other ways to achieve the same result of course, but this is an existing commonly used mechanism.)
