### ISSUE TITLE
Is "requestIdentity()" the best method name and do we need it?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/digital-credentials#61]
[As part of PR 57](https://github.com/WICG/digital-credentials/pull/57#discussion_r1465445128), @samuelgoto wrote:

> We don't have to do this all at once, but I'm wondering if something like a requestDigitalCredential may be a better (more specific ) method name in comparison to requestidentity ... again, because this is going to collide with Chrome's implementation of the IdentityCredential which FedCM uses.

We should consider some alternatives or decide if we are ok with `requestIdentity()`.

**Comment by tplooker** [comment]
I'd say this issue is some what related to #23 and the ongoing conversation about the future relationship this api might have to something like credential management. 

That aside for now though, I prefer API names like `get()` that are encapsulated under something that provides more of the context around the API's purpose like `identitycredential` `digitalcredential`, because it means in future if we add an issuance or `create` API there would be a logical place for it. For example a future state could be:

`identitycredential.get()` and `identitycredential.create()` or `identitycredential.store()`

**Comment by marcoscaceres** [comment]
That just gets us back to credential management (CM) though, which is where we started. 

The rationale for leveraging CM is described [here](https://github.com/WICG/digital-credentials/blob/main/digital-credentials-2-proposal.md#why-leverage-credential-management-api) and why we couldn't use `.get()` is described [here](https://github.com/WICG/digital-credentials/blob/main/digital-credentials-2-proposal.md#extensions-to-credential-management-api-requestidentity-method).

It basically comes down to `.get()` allowing mixing requesting credential  types, which is what we want to avoid. At the same time, I believe CM's `CredentialContainer` is still the right place to hang this off. We can leverage so much stuff from CM that it would be a shame if we ended up creating a new container for these credential types.

**Comment by marcoscaceres** [comment]
I'm ok with renaming the method to `.requestDigitalCredential()`.

**Comment by samuelgoto** [comment]
> allowing mixing requesting credential types, which is what we want to avoid. 

It is not clear to me that this is the case. 

Specifically, chrome expects the two party model (currently represented by FedCM) will have a big intersection in use cases with the three party model (in my mental model, this work), and we would like to design the API in such a way that a developer can request both at the same time so that the models can co-exist.

**Comment by bvandersloot-mozilla** [comment]
There are ways to design this to allow intermingling of the two-party model with the three-party model where appropriate without making these available via `.get()`. 

> **Clear Differentiation:** With requestIdentity(), we aim to prevent potential mix-ups between different request types, offering a clear distinction between tasks such as password retrieval and age verification (which could happen with using just the .get()method).

This point from the doc Marcos linked is the relevant bit. 

While it makes sense to allow FedCM to exist with this in UI surface because both can provide richer identity, it makes much less sense for a Passkey or password request to be able to be included.

**Comment by samuelgoto** [comment]
> While it makes sense to allow FedCM to exist with this in UI surface because both can provide richer identity, it makes much less sense for a Passkey or password request to be able to be included.

One of the earlier variations we looked at was to expose identity under `navigator.identity.get()`, as opposed to `navigator.credentials.get()` or `navigator.credentials.requestIdentity()`, which I think accomplishes much of these goals.

If we want to make a big separation, then subclassing `Credential` is only going to create problems: once you properly subclass `Credential` we would have make the `Credential` exposed to `get` and the other methods.

WDYT?

**Comment by bvandersloot-mozilla** [comment]
> If we want to make a big separation, then subclassing Credential is only going to create problems: once you properly subclass Credential we would have make the Credential exposed to get and the other methods.

Only if you don't define the [relevant credential interface objects](https://w3c.github.io/webappsec-credential-management/#credentialrequestoptions-relevant-credential-interface-objects) to specialize based upon what type of call it is and include the new Credential in the [Credential Type Registry](https://w3c.github.io/webappsec-credential-management/#sctn-cred-type-registry). It just is an unusual extension of the Credential type, which these certainly are. Since we are already defining our own registry, that could live alongside the other registry and Credentials could be put in whichever makes the most sense.


Let's stick to bikeshedding at Marcos's request though :)

**Comment by bvandersloot-mozilla** [comment]
`.requestDigitalCredential()` may be a little confusing, lining them up side by side:

`navigator.credentials.get()` vs `navigator.credentials.requestDigitalCredential()`

Someone not so deeply entrenched in this space may not get all of the meaning conveyed by "Digital" as the only modifier there. 

A bad idea to brainstorm on: `.requestCryptographicCredential()`.

**Comment by marcoscaceres** [comment]
The "digital" was supposed to represent the same thing as the "e" in email. What I was trying to convey with "digital" is that it's a "digital" counterpart to a "physical" credential (e.g., driver licenses, passports, etc.)... though there may be some credentials that don't have a physical counterpart in the future (certain documents might only come in digital form).


CryptographicCredential could be a good choice so long a it holds that these credentials always have cryptographic properties. That   could be a good assumption to make and something we reinforce somehow.

**Comment by marcoscaceres** [comment]
I'd like to rehash our discussion regarding the challenges posed by `.requestIdentity()` and summarize the potential solutions our group has identified so far. My aim is to provide an impartial overview of the issues and the proposed resolutions to allow us to make an informed choice amongst the possible solutions. 

Currently, we encounter a dilemma with this JavaScript code snippet:

```JS
const opts = {  publicKey , identity,  providers };
navigator.credentials.get(opts);
```

The core questions are: How do we determine priority when multiple members are present? What user interface (UI) should be displayed?

Possible solutions:

1.  Permit `.get()` to accept all combinations
2.  Modify `.get()` to select a preferred option
3.  Revise `.get()` to restrict by `type` and `option`
4.  Introduce a new method like `.requestWhateverCredential()` (currently proposed in #57)
5.  Establish a new namespace and methods, e.g., `navigator.identity.get()`

## 1. Permit .get() to accept all combinations

This approach raises concerns from a user experience (UX) and UI standpoint, primarily due to the lack of restrictions in the current Credential Management specification. This absence of constraints is precisely the issue we are currently facing (i.e., you don't know what you are going to get).

## 2. Modify .get() to select a preferred option

Altering `.get()` to automatically choose a preferred option may lead to inconsistent results across different browsers and their versions. Such variability could make it challenging for developers to anticipate the UI presented to users.

## 3. Revise .get() to restrict by `type` and `option`

We could propose to WebAppSec to modify the `.get()` method to a signature like `.get(DOMString type, object options)`. This change would enable specific type restrictions, potentially resolving the existing issues with `.get()`. Although this is a versatile solution applicable to both current and future types, it necessitates explicit dictionary creation for options. While backward compatible, it would require modifications in existing implementations.

This generic solution could be used for any existing and new type. However, the type registry would require adding explicit dictionary for creation `options` (the Credential Management spec has been encouraging the use of `partial` over extending IDL dictionaries, which would need to change). 

We would need to check if we need to make similar changes to `.create()` and `.store()`. At first glance, I think we should be ok, though `.create()` seems to have the same issues as `.get()`, in that it relies on partial dictionaries. We can cross that bridge when we get to it (or we can ask WebAppsSec to deal with it a the same time)  

## 4. Introduce a new method like `.requestWhateverCredential()`

This method explicitly deals with the type we are interested in and structures the request. Additionally, it's can be bound very tightly to the UI presented to users. 

However, it might lead to an expansion of the Credential Management API, potentially setting a precedent for adding numerous type-specific methods.

## 5. Establish a new namespace and methods, e.g., `navigator.identity.get()`

From a developer perspective, this solution is advantageous as it relocates semantics and functionality to a distinct namespace. It offers flexibility for future method additions. Yet, this approach might be somewhat redundant in implementation, as it could end up being a wrapper over existing Credential Management functionalities.

We must consider the potential for redundancy and the implications for existing Credential Management functionalities. For instance, developers might use the new method in conjunction with existing ones, as shown below:

```JS
const credential = await navigator.identity.get(requestData);
navigator.credentials.store(credential);
```

This scenario illustrates the possibility of overlapping functionalities and the need for consistency.

## Discussion

We can rule out "1.  Permit `.get()` to accept all combination", and "2.  Modify .get() to select a preferred option". They are not workable. 
 
"3 revise `.get()` to restrict by `type` and `option`" offers the most elegant and generalized solution. It offers new functionality while retaining backwards compatibly. 

Then "4. Introduce a new method like `.requestWhateverCredential()`" is basically a very specialized version of 3. 

Finally,  "5. Establish a new namespace and methods, e.g., `navigator.identity.get()`", has nice qualities/semantics for developers and provides us with a "clean slate". However, because it's a thin wrapper on top of `CredentialContainer`, we potentially still need to deal with interactions with, for instance, CredentialContainer's `.store()`.

**Comment by samuelgoto** [comment]
Thanks for putting this together, much appreciated!

> 3. Revise .get() to restrict by type and option

One variation of (3), is to introduce the `type` parameter to the [`CredentialRequestOption`](https://www.w3.org/TR/credential-management/#credentialrequestoptions-dictionary), which would allow us to keep the `get()` signature backwards compatible.

For example:

```javascript
await navigator.credentials.get({
  type: "something-to-say-that-we-dont-want-passkeys-passwords-just-fedcm-or-digital-credentials",
  identity: { /** two party model options */ },
  digital: { /** three party model options */ }
});
```

Does this make sense @marcoscaceres ?

**Comment by samuelgoto** [comment]
Was chatting with @npm1 and another alternative came up, which I think isn't captured here.

## 6 Throw `Error` for invalid combinations

Another alternative is to modify each of the credentials' [`DiscoverFromExternalSource`](https://www.w3.org/TR/credential-management/#algorithm-discover-creds) to allow them to throw errors when invalid combinations are passed.

```javascript
const opts = {  publicKey , identity,  providers };
navigator.credentials.get(opts); // throws error
```

For example, we could say in the spec "publicKey and identity cannot be asked in the get() at the same time" and throw an error when that happens. If/when browsers figure out how to ask a passkey and an identity assertion at the same time, we could remove that error.

**Comment by nsatragno** [comment]
Hi, Nina here from the Credential Manager API. Please allow me to chime in.

I completely agree that mixing credential types with incompatible security and privacy attributes is a sharp edge user agents should stay away from. However, an important piece of context for this discussion is that while the Credential Manager API was designed around allowing a relying party to request multiple credential types on the same call, this reality never manifested. Currently, [the only browsers supporting a credential type other than "public-key" (webauthn) are Chromium based browsers.](https://wpt.fyi/results/credential-management/credentialscontainer-create-basics.https.html?label=master&label=experimental&aligned). Chromium does not support requesting multiple credential types on the same javascript call, there exists a de facto priority list and only one type is ever processed per request. The architecture and UI affordances means that updating Chrome to support this would entail a sizable project.

For this reason, I don't believe permitting an `IdentityCredential` to be passed to `get` means we end up with a UX problem where identity credentials get shown alongside passwords, passkeys, or OTP codes. What I would prefer is if we codified allowing for only a single credential type to be processed per request as part of the specification (in effect, standardising a variation of the current reality); and allowed identity credentials to be passed to `get`. This is similar to [Sam's proposal above](https://github.com/WICG/digital-credentials/issues/61#issuecomment-1919790032), except we'd throw an error for any combination more than one credential type.

Thus, the web would get the benefits of reusing the Credential Manager framework while being intentional about the separation of credential types. If, in the future, we wanted to support mixing certain types together (for example, a password with a passkey), we can have that conversation and update the specification again, detailing which credentials are allowed to be intermingled.

Some more thoughts [the proposals above](https://github.com/WICG/digital-credentials/issues/61#issuecomment-1918373746):

1 is unworkable as stated by others, and 2 is essentially the current state. Throwing an error when multiple credential types are passed seems strictly better than choosing some arbitrary order, which feels like a developer footgun.

I don't think I completely understand 3. but needing to pass a string for a type as a first argument would at first glance not be backwards compatible.

4 and 5 are both viable. From the perspective of a relying party they are roughly equivalent to my proposal and I would not mind going this way if people felt strongly about it. Ultimately, a web developer probably doesn't care what the endpoint is called or the exact API shape, just what its behaviour is.

**Comment by marcoscaceres** [comment]
> I don't think I completely understand 3. but needing to pass a string for a type as a first argument would at first glance not be backwards compatible.

Sorry, yes. It's deliberately not backwards compatible: I was not aware of the non-standards throwing behavior exhibited by some user agent, so 3 was intended to both keep the current multi-type selection, while also giving us a new "clean slate" option that would be feature detectable. This is great news though, because we have a web-compatible escape hatch! 🥳 

Also, 3 is supposed to allow other dictionary types other than [`CredentialRequestOptions`](https://www.w3.org/TR/credential-management-1/#dictdef-credentialrequestoptions) - because (again) the Cred Man spec is using `partial dictionary` to add things to `CredentialRequestOptions` it makes things somewhat messy.  

To make this fixable in a fully web compatible way, we should use proper dictionary inheritance. 

Given this new information, I think we can now do a mix of 3 and 6. Bear with me!

1. We change the signature of `.get()` to `Promise<Credential?> get(optional object options);`;
2. In `.get()`, if object includes more than one known credential member type in <var>options</var>, throw `TypeError` (or whatever Chrome throws). If there are zero known properties, throw `TypeError`. 
3. Otherwise, there is only one valid property so we can discriminate on that:
3.1 let <var>memberName</var> be the known credential member.  
3.2 Switch on <var>memberName</var>:
3.2.1 Looking <var>memberName</var> in registry and construct appropriate IDL dictionary. Rethrow any exceptions. 
3.2.2 ... continue per normal... 

In JS, we could express this as:
```JS
navigator.credential.get = function (obj) {
    const allowedProperties = ["password", "federated", "whatever"];
    let foundProperty = null;

    // Find at least one property...
    for (const prop in obj) {
        if (allowedProperties.includes(prop)) {
            if (foundProperty) {
                throw new TypeError(
                    `Object contains more than one allowed property: '${foundProperty}' and '${prop}'.`
                );
            }
            foundProperty = prop;
        }
    }

    if (!foundProperty) {
        throw new TypeError(
            "Object does not contain any of the allowed properties. One is required."
        );
    }

    // Let's try to do the IDL conversion
    try {
        let dictionary;
        switch (foundProperty) {
            case "password":
                dictionary = new PasswordCredentialRequestOptions(options);
            case "federated":
                dictionary = new FederatedCredentialRequestOptions(options);
            case "whatever":
                dictionary = new WhateverCredentialRequestOptions(options);
        }
    } catch (IDLError) {
        throw IDLError; // re-throw it
    }
    // perform whatever steps are needed given the particular dictionary type... in parallel... bla bla..
   return new Promise(resolve) {
      // eventually
      resolve(credential);
   }
};
```

> Ultimately, a web developer probably doesn't care what the endpoint is called or the exact API shape, just what its behavior is.

Agree. 

So, WDYT? Could be do a combined 3 and 6 as per above?... I thinks it's kinda nice. 

And, as you mentioned, in the future, should we ever need to, we could have a special list that allows mixing request types (only for new types) should we ever need to without breaking backwards compat.

**Comment by marcoscaceres** [comment]
🧐... now that I'm looking at it again... we can keep the same signature for `.get()`, but we just need to add the one member check and throwing behavior. 

The rest stays the same, because the IDL type mapping happens automatically. 🎉

Ok, that's better and super simple/elegant.

**Comment by marcoscaceres** [comment]
Sorry, @nsatragno, I misread what you said about browsers throwing/rejecting if developers mix credential types. I thought that was already implemented today, and it's not.  

For example, this won't throw:

```JS
await navigator.credentials.get({password: "true", federated: {providers: ["https://google.com"]}});
```

And I see what you mean by Chrome acting on an adhoc priority list (with FedCM getting priority). 

If browsers don't already throw/reject, then we definitely risk introducing web compat issue.

That gets us back to option 3, I think.

**Comment by nsatragno** [comment]
Non chromium browsers throw (they only support one credential type after all). And since the priority list behaviour is useless to websites, I don't think we run a backwards web compat risk. Chromium can add a use counter before making the switch for safety.

I'll socialize this proposal with the webauthn wg as well.

**Comment by bvandersloot-mozilla** [comment]
I still think that it is worthwhile to maintain a different function for RWI and sign-in use cases. This feels like an important property to have to stem some induced demand and make it clear to developers that these are different operations. 

Among the options that have a new call site, I think a minor variation on 5 could work really well to preserve all of the niceties of the [solution reached earlier](https://github.com/WICG/digital-credentials/issues/61#issuecomment-1920545304) while keeping the API surface separate.

If we define a new class `Identity` that subclasses `Credential`, then we can define additional fields that all RWI types will need. The `DigitalCredential` can implement it, and if FedCM wants to be made available as a RWI it can extend `Identity` instead of `Credential`.  Semantically, a `Credential` is anything to identify yourself to a site, and an `Identity` is something corresponding to a RWI.

Then we can make `navigator.credentials` and `navigator.identities` two independent `CredentialsContainer`s. This reuses all of the logic of the credential container, however we would need to add the ability to maintain independent allowlists for the different types of `Credential` permitted in each container, like adding a second [Credential Type Registry](https://w3c.github.io/webappsec-credential-management/#sctn-cred-type-registry) and using the right one based upon the object used.

**Comment by samuelgoto** [comment]
> For example, this won't throw:
>
> await navigator.credentials.get({password: "true", federated: {providers: ["https://google.com"]}});

@nsatragno @marcoscaceres can't we just say in the CM spec that this is "one of the (current, and in the future many) cases where two specific credentials are supported at the same time"? That is, the fact that this doesn't throw, doesn't invalidate the proposal to "throw when digital credentials are requested with other types".

**Comment by samuelgoto** [comment]
> I think a minor variation on 5 could work really well to preserve all of the niceties of the https://github.com/WICG/digital-credentials/issues/61#issuecomment-1920545304 while keeping the API surface separate.

To be up front, a variation of (5) I think is workable. 

> If we define a new class Identity that subclasses Credential, then we can define additional fields that all RWI types will need. The DigitalCredential can implement it, and if FedCM wants to be made available as a RWI it can extend Identity instead of Credential. Semantically, a Credential is anything to identify yourself to a site, and an Identity is something corresponding to a RWI.

I think this could work and I'd be happy to explore this formulation further. I don't think `Identity` necessarily  means "real-world", but it may be that we just need to define these better (I think "government-issued" is more precise, meaning that we don't expect FedCM to be limited to this constraint).

> Then we can make navigator.credentials and navigator.identities two independent CredentialsContainers. This reuses all of the logic of the credential container, however we would need to add the ability to maintain independent allowlists for the different types of Credential permitted in each container, like adding a second [Credential Type Registry](https://w3c.github.io/webappsec-credential-management/#sctn-cred-type-registry) and using the right one based upon the object used.

This, in particular, is very compelling to me.

Having said that, let me try to break this down a bit:

> I still think that it is worthwhile to maintain a different function for RWI and sign-in use cases. This feels like an important property to have to stem some induced demand and make it clear to developers that these are different operations.

I'm struggling to share this intuition:

1) First, I don't think RWI is the right determining aspect of this API: it is the three party model (i.e. the introduction of the holder). Chrome is already getting interest on use cases that look nothing like RWI (assuming, by RWI, one means "government-issued identities"): tickets, membership cards, social profile cards, academic institutional affiliations and diplomas, payments, etc. We don't expect this API to be used exclusively for "government-issued" identities, and we expect much of the "online world" is going to feel represented by this API.
2) Second, identity verification is part of authentication, typically at account creation (sign-up) and account recovery. I agree that we don't want to use for Sign-in (developers should use first party cookies and passkeys for that), but authentication isn't just Sign-in: Signing-up is equally important, and I think, conceptually within the realm of the Credential Manager API. For example, we expect this API to be called while you are creating or augmenting accounts on websites (e.g. providing that you are over 18 to grant you access to different aspects of the website, or providing that you are a citizen when you are accessing governmental services). We are already seeing these credential appear in regulation in account creation/recovery flows.

Having said all this, I think @bvandersloot-mozilla 's proposal is a reasonable end state to me.

**Comment by nsatragno** [comment]
It looks to me that @bvandersloot-mozilla's proposal addresses all concerns posted on the issue elegantly.  No objections here to go with it.

**Comment by marcoscaceres** [comment]
Ok, cool. Liking this a lot!!! 

Just confirming: 

```WebIDL
// Our spec (or some other spec)
interface Identity : Credential {
  // future things here...
};

// In our spec (note we drop the "Credential" moniker in favor of "Identity", to make a clearer distinction with the pure *Credential types)
interface DigitalIdentity : Identity {
};
```

And we do (pleas note the singular "identity" - @samuelgoto expressed an interest in maybe calling it that instead... we can bikeshed that):

```WebIDL
partial interface Navigator { 
  [SecureContext, SameObject] readonly attribute CredentialsContainer identity; 
};
```

I think generally we can start with the above. I'll add it to #57. We should still endeavor to find something better than the "Digital" prefix before we expose this to the Web (@bvandersloot-mozilla had proposed maybe "Cryptographic"... we should come up with a few more options if we can).

**Comment by marcoscaceres** [comment]
@nsatragno, irrespective of the above, I think the problem with the use of `partial dictionary` remains in Cred Man. Do you think we could address that? Specially given that some user agents already throw. 

For our spec, I'd still like to do:
```JS
    dictionary DigitalIdentityRequestOptions : CredentialRequestOptions {
      required sequence&lt;IdentityRequestProvider&gt; providers;
    };
```

I can't do that with `partial dictionary` because obviously "required" would beak `CredentialRequestOptions` (plus I would also prefer if we can discriminate by dictionary).

**Comment by samuelgoto** [comment]
> I can't do that with partial dictionary because obviously "required" would beak CredentialRequestOptions 

Can't you use a partial, and just not handle the request in the DigitalCredential[[DiscoverFromExteenalSouece]] algorithm, which would lead to a null response?

**Comment by marcoscaceres** [comment]
We could, but it's still messy carrying around members we don't need. If we can fix it now, that would be nicer.

**Comment by marcoscaceres** [comment]
Tried to capture the discussion in PR #57.

Please take another look as I've renamed and reworded a bunch of things as a results.

**Comment by marcoscaceres** [comment]
Giving this more thought, all solutions lead to duck-typing as part of DigitalCredential[[DiscoverFromExternalSource]], so can live with it. We can leave `.get()` as is. 

I’ll update #57 to use a partial dictionary.

**Comment by samuelgoto** [comment]
> Tried to capture the discussion in PR https://github.com/WICG/digital-credentials/pull/57.

https://github.com/WICG/digital-credentials/pull/57 looks great to me. Trying to clarify a few things, but generally speaking I think captured the essence of @bvandersloot-mozilla 's proposal.
